#
# http://www.ros.org/wiki/amcl
# The first commented value is the default per the wiki
# The second commented value is the default per nav/amcl/examples
# The defaults in amcl_node.cpp are yet differant...
#

# Overall filter parameters
min_particles:        100
max_particles:        1000
kld_err:              0.01
kld_z:                0.99
update_min_d:         0.2
update_min_a:         0.3
resample_interval:    2
transform_tolerance:  0.7
recovery_alpha_slow:  0.001
recovery_alpha_fast:  0.1
initial_cov_xx:       0.25
initial_cov_yy:       0.25
initial_cov_aa:       0.06853
gui_publish_rate:     1.0
save_pose_rate:       0.5
use_map_topic:        true
first_map_only:       false
selective_resampling: false

# Laser Model Parameters
laser_min_range:            -1.0
laser_max_range:            -1.0
laser_max_beams:            180
laser_z_hit:                0.8
laser_z_short:              0.1
laser_z_max:                0.05
laser_z_rand:               0.05
laser_sigma_hit:            0.2
laser_lambda_short:         0.1
laser_likelihood_max_dist:  2.0
laser_model_type:           likelihood_field

# Odometry model parameters
odom_model_type:  diff-corrected
odom_alpha1:      0.2
odom_alpha2:      0.2
odom_alpha3:      0.2
odom_alpha4:      0.2
odom_alpha5:      0.2
odom_frame_id:    odom
base_frame_id:    base
global_frame_id:  map
tf_broadcast:     true
