controller_frequency: 1

TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: -1.0
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  min_in_place_vel_theta: 0.33

  acc_lim_theta: 0.8
  acc_lim_x: 0.8
  acc_lim_y: 0.8

  xy_goal_tolerance: 1.5
  yaw_goal_tolerance: 3

  sim_time: 3
  path_distance_bias: 0.5
  heading_lookahead: 1.5
  holonomic_robot: false
