controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 0.03
  min_vel_theta: -0.03
  min_in_place_vel_theta: 1

  acc_lim_theta: 3
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  xy_goal_tolerance: 1.5
  yaw_goal_tolerance: 3

  sim_time: 3
  path_distance_bias: 0.5
  heading_lookahead: 1.5
  holonomic_robot: false


