base_global_planner: navfn/NavfnROS  # Global planner type for Move Base
base_local_planner: dwa_local_planner/DWAPlannerROS # Local planner type for Move Base

#recovery_behaviors:
#  - name: back_up
##    type: move_back_recovery/MoveBackRecovery
  # - name: rotate_recovery
  #   type: rotate_recovery/RotateRecovery

controller_frequency: 7.0           # Frequency for the robot controller
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
recovery_behavior_enabled: true     # Enable recovery behaviors
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 0.0
max_planning_retries: -1
